#!/usr/bin/python
import pickle
import sqlite3
import datetime
import medManager
import userManager

print "Content-type: text/plain; charset=iso-8859-1\n";
first = 1;
print '[',
for med in medManager.getInventory(0):
  if(first == 0):
    print ',',
  first = 0
  print '{"name":"',
  print(med[1]), #name
  print '", "available":"',
  print(med[2]), #id
  print '", "id":"',
  print(med[0]), #total
  print '"}',
print ']';

#print '[{"name":"Tylenol", "available":"4", "id":"1"},{"name":"Vicodin", "available":"2", "id":"2"},{"name":"Advil", "available":"14", "id":"3"},{"name":"Alegra", "available":"1", "id":"4"},{"name":"Alegra D", "available":"1", "id":"5"},{"name":"Alegra S", "available":"1", "id":"6"},{"name":"Alegra X", "available":"1", "id":"7"},{"name":"Multi-Vitamin", "available":"20", "id":"8"}]';
