#!/usr/bin/python

import cgi, cgitb 
import subprocess

print "Content-type: text/plain; charset=iso-8859-1\n";

# Create instance of FieldStorage 
form = cgi.FieldStorage() 

#recieves:
#	message: text to say
#returns: 
#	success: 1/0

# Get data from fields
message = form.getvalue('message')

p1 = subprocess.Popen(['pico2wave -w /tmp/message.wav "%s"' % message], shell=True)
p1.wait()
p2 = subprocess.Popen(['aplay /tmp/message.wav'], shell=True)
p2.wait()

print '{"success":"1"}'

